### ISSUE TITLE
Using "latest" for dependency versions is dangerous

### ISSUE THREAD

**Issue by evansolomon** [Kikobeats/meaning-cloud#3]
In 36852cf1a3862955abba979829ff83d9bf5f4d5e all of the dependency versions changed to use `latest`. This means that any breaking changes in dependencies can end up being a breaking change here. For example, the [got](https://github.com/sindresorhus/got) module has changed to use some es6 code without transpiling it, so it now requires Node >=4. That means that all of the sudden this library also requires Node >=4.

This is just one example, but really any change could have the same effect.

In my experience it's very uncommon to use anything like `latest` a version range. It's much safer to keep a stricter version like you had before.

**Comment by Kikobeats** [comment]
It's true, I see the got update. Can you create a PR of this? :-)

**Comment by evansolomon** [comment]
I could make a PR but I'm not sure how you how you want this library to work. Maybe you want to require Node 4 or use some new feature of got that I'm not familiar with (I'd never heard of got until investigating this error).

**Comment by Kikobeats** [comment]
got 6 need >= 4 node.

Then we need to block to 5.x in package.json

**Comment by evansolomon** [comment]
I also don't know what versions you want for other dependencies. I could pick some myself but since I'm not that familiar with the code here I don't know what the best answers are.
